<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <LangVersion>latest</LangVersion>
        <Description>Simple and easy to use Among Us modding API.</Description>
        <PackageId>AllOfUs.MiraAPI</PackageId>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <NoWarn>IDE0031;IDE0032</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="Resources\**\*.*" />
    </ItemGroup>

    <ItemGroup>
      <EditorConfigFiles Remove="GameModes\.editorconfig" />
      <EditorConfigFiles Remove="Patches\GameModes\.editorconfig" />
      <EditorConfigFiles Remove="Patches\.editorconfig" />
    </ItemGroup>

    <Import Project="../AmongUs.props" />
</Project>
